package com.cds.cbit.accounts.customfields;

import com.portal.pcm.StrField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code> is used with the FList class to
 * specifiy which field is being accessed, and its type. The type information is used to provide
 * compile time type checking. These classes are auto generated.
 * 
 * @version 1.0 Thur Sep 12 16:39:05 IST 2019
 * 
 * @author Autogenerated
 */

public class LwFldPlanActDate extends StrField {

  private static final long serialVersionUID = 4411877162838877126L;

  /**
   * Constructs an instance of <code>LwFldPlanActDate</code>.
   */
  public LwFldPlanActDate() {
    super(20078, 5);
  }

  /**
   * Returns an instance of <code>LwFldPlanActDate</code>.
   * 
   * @return An instance of <code>LwFldPlanActDate</code>.
   */
  public static synchronized LwFldPlanActDate getInst() {
    if (me == null) {
      me = new LwFldPlanActDate();
    }
    return me;
  }

  private static LwFldPlanActDate me;
}