package com.cds.cbit.accounts.customfields;

import com.portal.pcm.IntField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code> is used with the FList class to
 * specifiy which field is being accessed, and its type. The type information is used to provide
 * compile time type checking. These classes are auto generated.
 * 
 * @version 1.0 Tue Feb 13 21:57:42 IST 2018
 * @author Autogenerated
 */

public class LwFldMobileNumber extends IntField {

  private static final long serialVersionUID = 1L;

  /**
   * Constructs an instance of <code>LwFldMobileNumber</code>.
   */
  public LwFldMobileNumber() {
    super(20007, 1);
  }

  /**
   * Returns an instance of <code>LwFldMobileNumber</code>.
   * 
   * @return An instance of <code>LwFldMobileNumber</code>.
   */
  public static synchronized LwFldMobileNumber getInst() {
    if (me == null) {
      me = new LwFldMobileNumber();
    }
    return me;
  }

  private static LwFldMobileNumber me;
}
